// Auto-generated from JSON schemas
// Do not edit this file directly

// Comment
export interface Comment {
  /** Unique identifier */
  id: number;
  /** Associated post ID */
  post_id: number;
  /** Comment author ID */
  user_id: number;
  /** Comment text */
  body: string;
  /** Creation timestamp */
  created_at?: string;
  /** Number of likes */
  likes?: number;
}

// Post
export interface Post {
  id?: number;
  user_id?: number;
  title?: string;
  body?: string;
  published?: boolean;
  created_at?: string;
  views?: number;
  likes?: number;
}

// Product
export interface Product {
  /** Unique identifier */
  id: number;
  /** Product name */
  name: string;
  /** Product description */
  description?: string;
  /** Product price */
  price: number;
  /** Price currency */
  currency?: string;
  /** Product category */
  category?: string;
  /** Brand name */
  brand?: string;
  /** Stock keeping unit */
  sku?: string;
  /** Available quantity */
  stock?: number;
  /** Product image URL */
  image?: string;
}

// Todo
export interface Todo {
  /** Unique identifier */
  id: number;
  /** Owner user ID */
  user_id?: number;
  /** Todo title */
  title: string;
  /** Completion status */
  completed: boolean;
  /** Due date */
  due_date?: string;
  /** Priority level (1-5) */
  priority?: number;
}

// User
export interface User {
  /** Unique identifier */
  id: number;
  /** Username */
  username: string;
  /** Email address */
  email: string;
  first_name?: string;
  last_name?: string;
  avatar?: string;
  gender?: 'male' | 'female';
  phone?: string;
  address?: string;
  city?: string;
  country?: string;
  created_at?: string;
}


// Resource helpers
export type ResourceName = 'comments' | 'posts' | 'products' | 'todos' | 'users';

export interface ResourceMap {
  comments: Comment;
  posts: Post;
  products: Product;
  todos: Todo;
  users: User;
}

// API response types
export type CollectionResponse<T extends ResourceName> = ResourceMap[T][];
export type SingleResponse<T extends ResourceName> = ResourceMap[T];
