#!/usr/bin/env node

/**
 * Generates TypeScript type definitions from JSON Schema files
 * Usage: node generate-types.js
 */

const fs = require('fs');
const path = require('path');

const SCHEMAS_DIR = path.join(__dirname, '..', 'shared', 'schemas');
const OUTPUT_FILE = path.join(__dirname, '..', 'web', 'types', 'api.ts');

// JSON Schema type to TypeScript type mapping
const typeMap = {
  string: 'string',
  integer: 'number',
  number: 'number',
  boolean: 'boolean',
  array: 'Array',
  object: 'Record<string, any>',
};

function jsonSchemaToTS(schema) {
  const { properties, title, required = [] } = schema;
  
  let typeDefinition = `export interface ${title} {\n`;
  
  for (const [propName, prop] of Object.entries(properties)) {
    const isRequired = required.includes(propName);
    const optional = isRequired ? '' : '?';
    const tsType = getTSType(prop);
    const description = prop.description ? `  /** ${prop.description} */\n` : '';
    
    typeDefinition += `${description}  ${propName}${optional}: ${tsType};\n`;
  }
  
  typeDefinition += '}\n';
  return typeDefinition;
}

function getTSType(prop) {
  if (prop.type === 'array' && prop.items) {
    const itemType = getTSType(prop.items);
    return `${itemType}[]`;
  }
  
  if (prop.type === 'object' && prop.properties) {
    // Nested object - create inline type
    let nestedType = '{\n';
    for (const [nestedName, nestedProp] of Object.entries(prop.properties)) {
      nestedType += `    ${nestedName}: ${getTSType(nestedProp)};\n`;
    }
    nestedType += '  }';
    return nestedType;
  }
  
  if (prop.enum) {
    return prop.enum.map(v => `'${v}'`).join(' | ');
  }
  
  return typeMap[prop.type] || 'any';
}

function generateResourceHelpers(schemas) {
  let helpers = '\n// Resource helpers\n';
  helpers += 'export type ResourceName = ';
  helpers += schemas.map(s => `'${s['x-resource'].name}'`).join(' | ');
  helpers += ';\n\n';
  
  helpers += 'export interface ResourceMap {\n';
  for (const schema of schemas) {
    helpers += `  ${schema['x-resource'].name}: ${schema.title};\n`;
  }
  helpers += '}\n\n';
  
  helpers += '// API response types\n';
  helpers += 'export type CollectionResponse<T extends ResourceName> = ResourceMap[T][];\n';
  helpers += 'export type SingleResponse<T extends ResourceName> = ResourceMap[T];\n';
  
  return helpers;
}

function main() {
  // Read all schema files
  const schemaFiles = fs.readdirSync(SCHEMAS_DIR)
    .filter(f => f.endsWith('.json'));
  
  if (schemaFiles.length === 0) {
    console.log('No schema files found in', SCHEMAS_DIR);
    return;
  }
  
  const schemas = [];
  let output = '// Auto-generated from JSON schemas\n';
  output += '// Do not edit this file directly\n\n';
  
  // Generate types for each schema
  for (const file of schemaFiles) {
    const schemaPath = path.join(SCHEMAS_DIR, file);
    const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
    schemas.push(schema);
    
    output += `// ${schema.title}\n`;
    output += jsonSchemaToTS(schema);
    output += '\n';
  }
  
  // Add helper types
  output += generateResourceHelpers(schemas);
  
  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  // Write output file
  fs.writeFileSync(OUTPUT_FILE, output);
  
  console.log(`✓ Generated TypeScript types for ${schemas.length} schemas`);
  console.log(`  Output: ${OUTPUT_FILE}`);
  console.log(`  Schemas: ${schemas.map(s => s.title).join(', ')}`);
}

main();
